name: Build & Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Login to GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/voidwatcher:latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/voidwatcher:latest .

      # Push the Docker image to GitHub Container Registry
      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/voidwatcher:latest

      # Push the Docker image to Docker Hub
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/voidwatcher:latest