name: Build & Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Login to GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Extract the tag name (e.g., v0.0.001)
      - name: Extract Tag
        id: extract_tag
        run: |
          TAG=$(echo $GITHUB_REF | cut -d'/' -f3)
          echo "Extracted tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # Build the Docker image with both latest and versioned tags
      - name: Build Docker Image
        run: |
          docker build \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/voidwatcher:latest \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/voidwatcher:${{ steps.extract_tag.outputs.tag }} \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/voidwatcher:latest \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/voidwatcher:${{ steps.extract_tag.outputs.tag }} .

      # Push the Docker image to GitHub Container Registry
      - name: Push to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/voidwatcher:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/voidwatcher:${{ steps.extract_tag.outputs.tag }}

      # Push the Docker image to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/voidwatcher:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/voidwatcher:${{ steps.extract_tag.outputs.tag }}